apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-server-data
  namespace: web-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: seaweedfs-storage
  resources:
    requests:
      storage: 2Gi
