apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-server-data
  namespace: web-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 2Gi
