apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - rbac.yaml
  - prometheus-config.yaml
  - prometheus.yaml
  - alertmanager.yaml
  - alertmanager-webhook.sops.yaml
  - node-exporter.yaml
  - kube-state-metrics.yaml
