apiVersion: v1
kind: Secret
metadata:
    name: nas-samba-credentials
    namespace: nas
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:kCT/2ek5xVxM9XIS1R0=,iv:aL+grpy0ydEKecoIh3xLH550bBgxssvU1T/H8aNCGDc=,tag:JIyMZ/pjsvfuUticG6nv9A==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSArNHArak5kSGJYMVkrSU82
            dmp6QjVSRDZZRVI0RnZIelhtbk5ZUW02SGdBCkh5SHdjUkFWR3JiejVQWmFjMDE5
            MTFGU2FRRTVuVktBVitKRmlhVVBVdmcKLS0tIGNGQUliVUQxUDhjSG55OGhXam8v
            VFA5OUJpc0Y0K0pscTRqdVp0RFN4R0UKgqaxyNM14ltIPCVHWj7I2JOVkWv0FeAe
            4VLhjR6GJKXXMd2EwFKNKB8rt8zNdcRHO24RWMkW42oWPPaNBF8OyQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1742pp7memrxpg9w9zm5m5aups35pkh9tqduzex802kawsec74aqq8xz3eu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:59:28Z"
    mac: ENC[AES256_GCM,data:1dlae4KlncsfaFEGlRfeORSlF84gqNLqhrCBauBHRj0HfGKiCqcw+uBbhsIRCd8qk4hIi97diZjeECtF35KJHpjPgDUgtQ3rw4WJeG9+IB7tEAGRzjfJc1c1VCyb7DppbRnelrm8ISde1Drcb/mRewRaC8slBld5aFRDW+xIePE=,iv:OwPSnp2271k6MAMoknJv2CDBX9CVhuwCFbHse7KbBW0=,tag:1N9B8JsCYjIS4D6U3y8o7Q==,type:str]
    version: 3.13.3
