apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nas-data
  namespace: nas
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: bulk-hdd
  resources:
    requests:
      storage: 200Gi
