apiVersion: v1
kind: Secret
metadata:
    name: nas-samba-credentials
    namespace: mount-watchdog
type: Opaque
stringData:
    password: ENC[AES256_GCM,data:VTJzdzXmMr/2HY6VZqw=,iv:viIYSUrBsd62E+h/3RU8ibyslfXHB3D14Eh9qP/NqTY=,tag:2AvRdwg0zfXyc62eQhwM1Q==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZem8wOURjS1ZMUmh5R3Yy
            MURXSngyWkJzSFhhOFo4MDdKenV3VW41R1RrCi90eFdDaGVvbUoveFY2cWhIQ1Ft
            eTJRM2NNblo5Ukd1WjBRNC83MGpDcjgKLS0tIGcrdkJ5RXAxU1QwWXYyMURUSnlV
            blhSaTRWNG9pN2ZaVmFjK2kxUW96QTgKBDL4jf1sffJ7l0aElG8n0uvBcsojoCGF
            t2v7lY6/VW9lu4IJZ2eBx7UiEv7yU0Ymb09rF1LCc0TqzzncovqS8A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1742pp7memrxpg9w9zm5m5aups35pkh9tqduzex802kawsec74aqq8xz3eu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:59:28Z"
    mac: ENC[AES256_GCM,data:3ICfeThO/w3u0pZTbofBdAhzPlQrUgzucQAE4Pi3hzCH7O1K5lZurMRdK3IdZGxh7i7HRDEyECTZ+ArhJnkP4PY8sIRT5rSAiB1Nni/+vwxuqHWsJY5slhxVjqumNGVdsE7S36D/H0EGJy9Rp+adlFjsu6pWX3CQ8UUCniZrxH0=,iv:1/+/fYeZ+4cCYuBTKi0jljqA4gSrpY4uSMRBE2ReUUk=,tag:fWuBX7VvFM/9o2WqUdEvvw==,type:str]
    version: 3.13.3
