apiVersion: v1
kind: Secret
metadata:
    name: seaweedfs-s3-credentials
    namespace: seaweedfs
type: Opaque
stringData:
    admin_access_key_id: ENC[AES256_GCM,data:UOXndRK8+sNZE7NnXrifj8xgmkA=,iv:/VT5aBgHpDeHAHVZOopSsYsxyHmaUwfMzsevlBrhSqM=,tag:t95UPZwoKlyTKJekb42YwA==,type:str]
    admin_secret_access_key: ENC[AES256_GCM,data:+IG0PzgM1mmlsEpGTDpkR37gw3wjOK7wz2BAT1jLvQH004Skyc5ZiQ==,iv:+HCs8c6SckvRV6TZvWRoPB7z86ky0dB8EvCgqDRbyvU=,tag:bBTXSFbc5egRZFghS/AlKg==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiV201VWZLM2hxQWNNZlJR
            VWVSdFgxVkp1YjZCd0x1NjNLQ2d2WFJNUkNRCm1SbmhIM0dHZ2RxN1ByMUE4Q0pM
            NWQxbW04aCtmTWRid2FXK096cmM1eEUKLS0tIGRqYXlWcFNSeCtTMVRwUE96SHBx
            L1g2eXEzY3VqajYxcXRMakp6ZE1HKzgKexEgWJppXQRp9ZqMeFjm9Hi/Qtk1mLOJ
            Jh3n+m8nOmZUiAXPgB5ZX7nr6DDM9WbyPi4fTvHcgtwsQ10x8OVYMg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1742pp7memrxpg9w9zm5m5aups35pkh9tqduzex802kawsec74aqq8xz3eu
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-10-07T21:59:28Z"
    mac: ENC[AES256_GCM,data:dfTTlvyYES/Qa8/SU/tRU3RGzTykEwA3hfSXtsr0lCgkHGZfib/uB4x0Wi1I4SSCfMMuCuCAWxz91mTt6FCD9NJCOXxHlFdXG42Ivo80kZX6SX9oLYPqKtDp1zlqgT4SqVD+ZO+QkozvsAqTNUi2gRctMaGuP7tixdlKNLzYsU8=,iv:l5I/kpWYz+jCaQvvsUTl4XnqdK/6LH9XWhXcdRKeMUI=,tag:WvsJT4ygA/FFwUtXTWVRtQ==,type:str]
    version: 3.13.3
